---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
          component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 8iu7*IU&
          - name: MYSQL_DATABASE
            value: chatscrum
        ports:
        - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:2.8
        ports:
        - containerPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatscrum
spec:
  replicas: 2
  selector:
    matchLabels:
      component: chatscrum
  template:
    metadata:
     labels:
        component: chatscrum
    spec:
      containers:
      - name: chatscrum
        image: diamondeyes/chatscrum:v1
        ports:
        - containerPort: 5000
        - containerPort: 5100






