---

 apiVersion: v1
 kind: Service
 metadata:
   name: redis-cluster-ip-service
 spec:
   type: ClusterIP
   selector:
     component: redis
   ports:
      - port: 6379
      #targetPort: 6379


---

 apiVersion: v1
 kind: Service
 metadata:
   name: mysql-cluster-ip-service
 spec:
   type: ClusterIP
   selector:
     component: mysql
   ports:
    - port: 3306
      #targetPort: 3306


---

 apiVersion: v1
 kind: Service
 metadata:
   name: chatscrum
   labels:
     component: chatscrum
 spec:
   type: NodePort #Exposes the service as a node ports
   ports:
   - port: 5000
     name: chat-appa
     protocol: TCP
     targetPort: 5000
     nodePort: 30500
   - port: 5100
     name: chat-appb
     protocol: TCP
     targetPort: 5100
     nodePort: 30051
   selector:
     component: chatscrum
