# Generated by Django 2.1.2 on 2018-11-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0003_auto_20181103_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ends_on', models.DateTimeField()),
                ('goal_project_id', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
            ],
        ),
    ]
