# Generated by Django 2.1.2 on 2018-11-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0004_scrumsprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumsprint',
            name='project',
        ),
    ]
