# Generated by Django 2.1.2 on 2018-11-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0005_remove_scrumsprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject'),
            preserve_default=False,
        ),
    ]
