# Generated by Django 2.1.2 on 2018-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0006_scrumgoal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumgoal',
            name='time_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scrumsprint',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
