# Generated by Django 2.1.2 on 2018-11-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0007_auto_20181110_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='moveable',
            field=models.BooleanField(default=True),
        ),
    ]
