# Generated by Django 2.1.2 on 2018-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0008_scrumgoal_moveable'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
