# Generated by Django 2.1.2 on 2018-11-29 13:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0009_scrumgoal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumgoal',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
