# Generated by Django 2.1.2 on 2018-12-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0010_auto_20181129_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumGoalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.IntegerField(default=-1)),
                ('goal_project_id', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=-1)),
                ('time_created', models.DateTimeField()),
                ('file', models.ImageField(blank=True, null=True, upload_to='media')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProjectRole')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
