# Generated by Django 2.1.2 on 2018-12-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0011_scrumgoalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumgoalhistory',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
