# Generated by Django 2.1.2 on 2018-12-04 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0012_auto_20181204_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoalhistory',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumGoal'),
            preserve_default=False,
        ),
    ]
