# Generated by Django 2.1.2 on 2018-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0013_scrumgoalhistory_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoalhistory',
            name='done_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
