# Generated by Django 2.1.2 on 2018-12-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0014_scrumgoalhistory_done_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoalhistory',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
