# Generated by Django 2.1.2 on 2019-01-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0015_scrumgoalhistory_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumProjectSlask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_client_id', models.TextField(blank=True, null=True)),
                ('slack_client_secret', models.TextField(blank=True, null=True)),
                ('slack_verification_token', models.TextField(blank=True, null=True)),
                ('slack_bot_user_token', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
