# Generated by Django 2.1.2 on 2019-01-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0016_scrumprojectslask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumProjectSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_client_id', models.CharField(max_length=50)),
                ('slack_client_secret', models.CharField(max_length=50)),
                ('slack_verification_token', models.CharField(max_length=50)),
                ('slack_bot_user_token', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='scrumprojectslask',
            name='project',
        ),
        migrations.DeleteModel(
            name='ScrumProjectSlask',
        ),
    ]
