# Generated by Django 2.0.6 on 2018-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0002_auto_20180731_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumgoal',
            options={'ordering': ['-id']},
        ),
    ]
