# Generated by Django 2.1.2 on 2018-11-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0002_scrumsprint_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumsprint',
            name='project',
        ),
        migrations.DeleteModel(
            name='ScrumSprint',
        ),
    ]
