# Generated by Django 2.1.7 on 2019-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0002_auto_20190124_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumuser',
            name='slack_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
