# Generated by Django 2.1.7 on 2019-03-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0003_scrumuser_slack_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProjectRole')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
