# Generated by Django 2.1 on 2019-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0004_scrumnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='scrumchatmessage',
            name='date_Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='color',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
