# Generated by Django 2.1.7 on 2019-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0004_scrumnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
