# Generated by Django 2.0.6 on 2018-09-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0004_auto_20180903_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
            ],
        ),
        migrations.RemoveField(
            model_name='scrumgoal',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scrumuser',
            name='projects',
        ),
        migrations.AlterField(
            model_name='scrumgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProjectRole'),
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumUser'),
        ),
    ]
