# Generated by Django 2.1.7 on 2019-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0005_auto_20190419_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='days_failed',
            field=models.IntegerField(default=0),
        ),
    ]
