# Generated by Django 2.1.7 on 2019-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0005_scrumemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumchatmessage',
            name='date_Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='color',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
