# Generated by Django 2.1.7 on 2019-05-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0006_auto_20190401_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='days_failed',
            field=models.IntegerField(default=0),
        ),
    ]
