# Generated by Django 2.0.6 on 2018-10-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0006_scrumdemoproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrumChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='scrumgoal',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scrumproject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='scrumchatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumChatRoom'),
        ),
    ]
