# Generated by Django 2.1.7 on 2019-07-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0009_auto_20190624_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='message_exist',
            field=models.BooleanField(default=False),
        ),
    ]
