# Generated by Django 2.2.4 on 2019-08-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0009_auto_20190624_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumWorkId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workid', models.TextField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProjectRole')),
            ],
        ),
    ]
