# Generated by Django 2.2.4 on 2019-09-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0011_auto_20190826_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='message_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScrumLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProjectRole')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
