# Generated by Django 2.2.4 on 2019-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0012_auto_20190903_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumgoal',
            name='push_id',
            field=models.CharField(default='Null Value', max_length=100),
        ),
    ]
