# Generated by Django 2.1.7 on 2020-01-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0014_chatmessage_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='project_name',
        ),
        migrations.AddField(
            model_name='connection',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject'),
            preserve_default=False,
        ),
    ]
