# Generated by Django 2.0.7 on 2020-04-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0015_auto_20200112_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://secure.gravatar.com/avatar/8ca9b9d6ee37371cba9ee9362cdbbc9b.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F00b63%2Fimg%2Favatars%2Fava_0005-512.png', null=True),
        ),
    ]
