# Generated by Django 2.0.7 on 2020-04-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0016_chatmessage_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(default='', max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='slack_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.ChatSlack'),
        ),
    ]
