# Generated by Django 2.0.7 on 2020-04-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0017_auto_20200422_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='slack_id',
        ),
        migrations.AddField(
            model_name='chatslack',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.ChatMessage'),
        ),
        migrations.AlterField(
            model_name='chatslack',
            name='slack_user_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
