# Generated by Django 2.0.7 on 2020-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0018_auto_20200422_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatslack',
            name='user',
        ),
        migrations.AddField(
            model_name='chatslack',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
