# Generated by Django 2.0.7 on 2020-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0019_auto_20200423_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumslack',
            name='access_token',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
