# Generated by Django 2.0.7 on 2020-04-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0021_auto_20200424_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500)),
                ('team_name', models.CharField(max_length=500)),
                ('team_id', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=500)),
                ('access_token', models.CharField(max_length=500, null=True)),
                ('bot_user_id', models.CharField(max_length=500, null=True)),
                ('bot_access_token', models.CharField(max_length=500, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumChatRoom')),
                ('scrumproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='scrumslack',
            name='bot_access_token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrumslack',
            name='bot_user_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
