# Generated by Django 2.0.7 on 2020-05-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0023_chatslack_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatslack',
            options={'ordering': ['-id']},
        ),
    ]
