# Generated by Django 2.0.7 on 2020-05-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0024_auto_20200519_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatslack',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='scrumsprint',
            options={'ordering': ['-id']},
        ),
    ]
