# Generated by Django 2.0.7 on 2020-05-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0025_auto_20200519_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumsprint',
            options={'ordering': ['id']},
        ),
    ]
