# Generated by Django 2.0.7 on 2020-07-08 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scrum', '0026_auto_20200520_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumslack',
            name='scrum_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
