# Generated by Django 2.0.6 on 2018-09-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumuser',
            old_name='project',
            new_name='projects',
        ),
    ]
