# Generated by Django 2.0.6 on 2018-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0003_remove_scrumuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='goal_project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrumproject',
            name='project_count',
            field=models.IntegerField(default=0),
        ),
    ]
