# Generated by Django 2.0.6 on 2018-10-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0007_auto_20181013_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='hours',
            field=models.IntegerField(default=-1),
        ),
    ]
