# Generated by Django 2.1.2 on 2018-11-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0008_scrumgoal_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.ScrumProject')),
            ],
        ),
        migrations.AddField(
            model_name='scrumgoal',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=1000000),
            preserve_default=False,
        ),
    ]
